name: morning_call
on:
  workflow_dispatch:
  schedule:
    # 代表国际标准时间21点30分，北京时间需要+8小时，代表北京时间上午5点30分点运行
    - cron: '30 23 * * *'
jobs:
  build:
    name: Build
    runs-on:  ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
            go-version: 1.19
        id: go

      - name: Check out source code
        uses: actions/checkout@v2

      - name: go get
        run:  go get

      - name: Build
        run: go build

      - name: Test
        run: ./morning_call
